Bug:
When deleting lots of text:
Error: file.startRow=1038 grid.length=899 file.partStartRow=0
at File.checkGrid (File.js:469)
at File.createCaret (File.js:213)
at File.deleteTextRange (File.js:1151)
at File.deleteSelection (File.js:1230)
at Object.keydel [as fun] (keyboard_delete.js:22)
at keyIsDown (editor.js:3776)

due to file.startRow wasnt updated/corrected.

file.scrollToCaret() will/probably set it correct