"Likely breaking change in Node 18:
/srv/webide/node_modules/ssh2/lib/protocol/SFTP.js:3389
  this.closed = false;
              ^

TypeError: Cannot set property closed of #<Readable> which has only a getter
    at new ReadStream (/srv/webide/node_modules/ssh2/lib/protocol/SFTP.js:3389:15)
    at SFTP.createReadStream (/srv/webide/node_modules/ssh2/lib/protocol/SFTP.js:305:12)
    at hash (/srv/webide/server/server_api.js:256:14)"