"Nodejs v4.2.6
/srv/nodejs/jzedit/node_modules/ssh2-streams/lib/constants.js:239
var KEX_BUF = Buffer.from(DEFAULT_KEX.join(','), 'ascii');
                     ^

TypeError: ascii is not a function
    at Function.from (native)
    at Function.from (native)
    at Object.<anonymous> (/srv/nodejs/jzedit/node_modules/ssh2-streams/lib/constants.js:239:22)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/srv/nodejs/jzedit/node_modules/ssh2-streams/lib/keyParser.js:23:17)
"